/**
 * http://dicomlookup.com/modalities.asp
 */

module.exports = Object.freeze({
    CR: 'CR',
    CT: 'CT',
    MR: 'MR',
    US: 'US',
    OT: 'OT',
    BI: 'BI',
    CD: 'CD',
    DD: 'DD',
    DG: 'DG',
    ES: 'ES',
    LS: 'LS',
    PT: 'PT',
    RG: 'RG',
    ST: 'ST',
    TG: 'TG',
    XA: 'XA',
    RF: 'RF',
    RTIMAGE: 'RTIMAGE',
    RTDOSE: 'RTDOSE',
    RTSTRUCT: 'RTSTRUCT',
    RTPLAN: 'RTPLAN',
    RTRECORD: 'RTRECORD',
    HC: 'HC',
    DX: 'DX',
    NM: 'NM',
    MG: 'MG',
    IO: 'IO',
    PX: 'PX',
    GM: 'GM',
    SM: 'SM',
    XC: 'XC',
    PR: 'PR',
    AU: 'AU',
    EPS: 'EPS',
    HD: 'HD',
    SR: 'SR',
    IVUS: 'IVUS',
    OP: 'OP',
    SMR: 'SMR'
});